### ISSUE TITLE
Cannot close tooltip through a button on a non-modal pop-up

### ISSUE THREAD

**Issue by jingzhaoou** [yjose/reactjs-popup#20]
I really like this plugin as it is amazingly small and powerful. However, I just get stuck on one issue. I tried to add a button on the tooltip and allow people to allow the pop-up by clicking that button. 

I am following the example at [Controlled Popup](https://react-popup.netlify.com/controlled-popup/). Rather than using a modal, I tried to change the example to use tooltip (e.g., using trigger). In that case, the pop-up was not closing when I invoked `closeModal()`.

**Comment by yjose** [comment]
Thank you @jingzhaoou ,
I cant understood correctly what you need to implement using the reactjs-popup, can you provide me an example using the sandbox issue template here https://codesandbox.io/s/n5q4zqw2n0
thanks

**Comment by jingzhaoou** [comment]
I appreciate your prompt reply and help. A simple example is provided at [here](https://codesandbox.io/s/y042vpxo1x). Click on the "x" button on the pop-up and nothing happens.

**Comment by yjose** [comment]
Hi @jingzhaoou ,
As you can see in this code sandbox example you can use a function as a child in your tooltip content and you would have access to the `close` function.  https://codesandbox.io/s/r0qnzpvz4p
the reason why your first example will not work as you expected because when you use a trigger in a Popup component the trigger element will be overridden by another react element to add a ref to calculate the position and onClick action.

Lets me know if you have any other Help !!

**Comment by jingzhaoou** [comment]
Thanks a lot for your help! Yeah, that meets my needs exactly. I can now remove `reactstrap` and place it with `reactjs-popup`  as I only needs pop-ups for my sites. Cheers!
