### ISSUE TITLE
Hooks Rewrite (proposal) 

### ISSUE THREAD

**Issue by yjose** [yjose/reactjs-popup#55]
### Reactjs-popup Hooks Rewrite
Discussion and Demos  about the  new reactjs-popup Rewrite using Hooks ( proposal ) 

* Please make sure you read the contributing Guide  https://github.com/yjose/reactjs-popup/blob/master/CONTRIBUTING.md
* use `hooks` branch  too open PR
* you can use our code sandbox starter https://codesandbox.io/s/lxzq8y240z

**Comment by shdq** [comment]
Don't rewrite your components! © Dan Abramov

**Comment by raRaRa** [comment]
Adding support for hooks would be really great. A potential way of using it would be something like:

```
const triggerRef = useRef()

usePopup(triggerRef, { ... optional options })

return (
    <h1 ref={triggerRef}>Hover over me</h1>
)
```

What do you think @yjose - has there been any progress on this?

Thanks!

**Comment by yjose** [comment]
yeah @raRaRa it has been a while now when I start working on hooks version. but to be honest, until this moment  I just I rewrite the component using hooks so the API and how to use it is still the same.

I can't find a simple way to provide a hooks way API  like what you mentioned in your component.  
can you elaborate more on how we can provide a simple API  (tooltip, modal ...)?

**Comment by avin-kavish** [comment]
@shdq 
> Don't rewrite your components! © Dan Abramov

Except this is a component library meant for consumption by other projects and since new projects expect hooks support, it might be worth it.

@yjose 
Since this is a visual component, I don't think hooks can change the way it is used. But re-writing in hooks _may_ lead to performance benefits if the `useEffect` hook is used as it is not render blocking. But if `useLayoutEffect` is needed, it might be the same as using classes.
