### ISSUE TITLE
`position` enum doesn't include 'center center'

### ISSUE THREAD

**Issue by spsaucier** [yjose/reactjs-popup#80]
`"center center"` is a valid position for the Popup, as it can be set to cover the initial element directly. However, it is rejected by the propTypes Enum.

I'm aware that it's not specifically code for and is effectively the same as `"blah blah"`, but it works for our use-case and ought not present an error.

### Version
1.3.2

### Test Case
https://codesandbox.io/s/m33m9q3np8

### Expected Behavior
`position` value is accepted

### Actual Behavior
```
Warning: Failed prop type: Invalid prop `position` supplied to `Popup`.
```

**Comment by yjose** [comment]
Yeah, @spsaucier, I thought no one will need the `"center center"`position, but look like it can be set to cover the initial element directly. 
I think you need to open a pull request if you have time to remove the prototype warning by adding the ` center center` position as a possible Positions ( don't miss the ts file and documentation :) ).
also, you need to mention that the developer needs to set `arrow={false}`  because `center center` arrow position will not be supported.
lets me know if you need some help !
